AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the OpenShift::OCP::Cluster resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: openshift.ocp.cluster.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/openshift-ocp-cluster-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: openshift.ocp.cluster.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/openshift-ocp-cluster-handler-1.0-SNAPSHOT.jar

